[package]
name = "dshuf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
drand-verify = "0.4.0"
hex = "0.4.3"
nois = "0.6.0"
